version: '3.7'

services:
  build-thali:
    image: thyrlian/android-sdk:latest

    working_dir: /src
    entrypoint: ./gradlew install

    volumes:
     - maven-repo:/root
     - ./Tor_Onion_Proxy_Library:/src

  build-whirlpool-client:
    image: maven:latest

    working_dir: /src
    entrypoint: mvn clean install -Dmaven.test.skip=true

    volumes:
     - maven-repo:/root
     - ./whirlpool-client:/src

volumes:
  # share maven local repository between containers
  maven-repo:
